image: thecodingmachine/php:7.3-v2-cli-node10

pipelines:
  default:
    - step:
        caches:
          - composer
          - node
        script:
          - pecl install pcntl exif bcmath
          - docker-php-ext-install pcntl exif bcmath
          - composer install
          - ln -f -s .env.pipelines .env
          - php artisan migrate
          - php artisan serve &
          - sleep 5
          - vendor/bin/phpunit
        services:
          - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'